version: '3'
services: 
    app: 
       container_name: genie
       restart: always
       build: .
       ports:
         - '80:5000'
      links:
        - mongo
    mongo:
        container_name: 127.0.0.1
        image: mongo
        ports:
          - '27017:27017'

       
